services:
  tsdb:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    build: .
    command: migrate
    depends_on:
      tsdb:
        condition: service_healthy
        restart: true
  web:
    build: .
    command: runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    depends_on:
      tsdb:
        condition: service_healthy
        restart: true
