# Generated by Django 5.1.1 on 2024-10-01 10:50

import timescale.db.models.fields
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension("postgis"),
        CreateExtension("timescaledb"),
        migrations.CreateModel(
            name='OrbitVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('posx', models.FloatField(editable=False)),
                ('posy', models.FloatField(editable=False)),
                ('posz', models.FloatField(editable=False)),
                ('velx', models.FloatField(editable=False)),
                ('vely', models.FloatField(editable=False)),
                ('velz', models.FloatField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
